let productsList = [
  {
    id: 1,
    name: "Apple iPhone 13 Pro Max ",
    price: 25500,
    brand: "Apple",
    series : "High Tier",
    img0: "imgs/products/1promax.jpg",
    img1: "imgs/products/promax.jpg",
    img2: "imgs/products/promax1.jpg",
    img3: "imgs/products/promax2.jpg",
    img4: "imgs/products/promax3.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "This is Apple iPhone 13 Pro Max. This is designed as per the prevailing industry standards, it scores high on the aspect of utility. The quality material used in its construction makes it durable. ",
  },
  {
    id: 2,
    name: "Samsung Galaxy A52 ",
    price: 6888,
    brand: "Samsung",
    series : "Mid Tier",
    img0: "imgs/products/1a52.jpg",
    img1: "imgs/products/a52.jpg",
    img2: "imgs/products/a521.jpg",
    img3: "imgs/products/a522.jpg",
    img4: "imgs/products/a523.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "Display Type:  Super AMOLED, 90HzDisplay Size:  6.5 inchesDisplay Resolution: 1080 x 2400 pixelsTouch Screen: YESProcessor Chipset: Qualcomm SM7125 Snapdragon 720G (8 nm)Processor CPU: Octa-coreMemory Internal: 128 GBMemory RAM: 8 GBMemory Card Slot Up To 1TBOperating System: Android ",
  },
  {
    id: 3,
    name: "Reno 6 Black Dual Sim",
    price: 8333,
    brand: "Reno",
    series : "Mid Tier",
    img0: "imgs/products/1reno6.jpg",
    img1: "imgs/products/reno6.jpg",
    img2: "imgs/products/reno61.jpg",
    img3: "imgs/products/reno62.jpg",
    img4: "imgs/products/reno63.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "The OPPO Reno6 features up to 8 GB + 128 GB of internal storage for all your memories. And, in case that’s not enough, you can enjoy its RAM expansion capabilities as well This mobile phone features a fingerprint-proof finish for an aesthetic appeal. And, with the Flash Snapshot powered by OPPO exclusive Image Clear Engine and Color Temperature Sensor, the mobile phone can automatically focus as soon as you kickstart the camera. ",
  },
  {
    id: 4,
    name: "Nokia 106 Dual SIM",
    price: 415,
    brand: "Nokia",
    series : "Low Tier",
    img0: "imgs/products/1nokia106.jpg",
    img1: "imgs/products/nokia106.jpg",
    img2: "imgs/products/nokia1061.jpg",
    img3: "imgs/products/nokia1062.jpg",
    img4: "imgs/products/nokia1063.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "Made from tough polycarbonate, Nokia 106 is built to last. Its inherent coloring means the color runs through the material, which makes scratches less detectable. Thanks to the contoured design, Nokia 106 fits perfectly in your hand. ",
  },
  {
    id: 5,
    name: "Apple iPhone 13",
    price: 21150,
    brand: "Apple",
    series : "High Tier",
    img0: "imgs/products/1iphone13.jpg",
    img1: "imgs/products/iphone13.jpg",
    img2: "imgs/products/iphone131.jpg",
    img3: "imgs/products/iphone132.jpg",
    img4: "imgs/products/iphone133.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "iPhone 13. The most advanced dual-camera system ever on iPhone. Lightning-fast A15 Bionic chip. A big leap in battery life. Durable design. And a brighter Super Retina XDR display. ",
  },
  {
    id: 6,
    name: "Xiaomi Redmi Note 11",
    price: 4899,
    brand: "Xiaomi",
    series : "Mid Tier",
    img0: "imgs/products/1redmi11.jpg",
    img1: "imgs/products/redmi11.jpg",
    img2: "imgs/products/redmi111.jpg",
    img3: "imgs/products/redmi112.jpg",
    img4: "imgs/products/redmi113.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "90Hz AMOLED Pioneer (Snapdragon® 680,90Hz AMOLED DotDisplay,33W Pro fast charging). The all-new Redmi Note 11 features a trendy flat frame design with a minimalist style. Immerse yourself in a world of wonderThe backlit display delivers the ultimate in brightness, contrast, colour calibration and resolution.90Hz high refresh rate Seamless touchscreen and display Enjoy your content in smooth and seamless 90Hz high refresh rate. Scroll through your social media feeds in comfort, or experience powerful and responsive gaming. 6nm Snapdragon® 680 All-round performance,",
  },
  {
    id: 7,
    name: "Realme C21",
    price: 4500,
    brand: "Realme",
    series : "Low Tier",
    img0: "imgs/products/1realmec.jpg",
    img1: "imgs/products/realmec.jpg",
    img2: "imgs/products/realmec1.jpg",
    img3: "imgs/products/realmec2.jpg",
    img4: "imgs/products/realmec3.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "Packed with a host of features, it scores high on the aspect of functionality. The fact that it ensures a seamless user-interface makes it worth the buy. ",
  },
  {
    id: 8,
    name: "OPPO A95",
    price: 6880,
    brand: "OPPO",
    series : "Mid Tier",
    img0: "imgs/products/1oppoa.jpg",
    img1: "imgs/products/oppoa.jpg",
    img2: "imgs/products/oppoa1.jpg",
    img3: "imgs/products/oppoa2.jpg",
    img4: "imgs/products/oppoa3.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "Having it for the first time ever in an A series, Reno Glow makes A95 not just stunning but also durable from scratches and fingerprints. Stand out from the rest without worrying from any damage caused by daily usage. With a powerful SoC and Octa-core processor, say goodbye to unnecessary waiting or interruptions whenever you watch your favorite shows. It also comes with excellent power consumption which allows you to get the best gaming experience. ",
  },
  {
    id: 9,
    name: "Xiaomi 11T Dual SIM",
    price: 8888,
    brand: "Xiaomi",
    series : "High Tier",
    img0: "imgs/products/1xiaomit.jpg",
    img1: "imgs/products/xiaomit.jpg",
    img2: "imgs/products/xiaomit1.jpg",
    img3: "imgs/products/xiaomit2.jpg",
    img4: "imgs/products/xiaomit3.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "The latest and most powerful MediaTek 5G chipset with dual 5G SIM and integrated 5G modem ensures smooth operation and efficient power consumption. 22% Faster CPU performance, 25% Power efficiency improved and 3.0GHz High frequency ultra core. 5000mAh battery + 67W turbo charging: The second-generation nano silicon oxide anode material with a lithium ion storage has a capacity that's ten times that of the conventional graphite anode material. This significantly improves the battery capacity and charging speed",
  },
  {
    id: 10,
    name: "OPPO Reno 6 ",
    price: 10115,
    brand: "OPPO",
    series : "High Tier",
    img0: "imgs/products/1oppo6.jpg",
    img1: "imgs/products/oppo6.jpg",
    img2: "imgs/products/oppo61.jpg",
    img3: "imgs/products/oppo62.jpg",
    img4: "imgs/products/oppo63.jpg",
    category: "mobiles",
    stars: 4,
    description:
      "Power You Get Day and Night : Our All-Day Intelligent Battery (4300mAh) harnesses power maxing out Combined with a new power-efficient display and processor, it could get you through the workday and late-night fun High-Res Triple Camera : Reno 6 smart phone is more suitable for those who love the aesthetics, it looks gorgeous and classy In terms of technology innovation and camera quality OPPO is the king in class",
  },
  {
    id: 11,
    name: "Samsung 40 inch FHD Smart",
    price: 5699,
    brand: "Samsung",
    series : "Mid Tier",
    img0: "imgs/products/1sfhd.jpg",
    img1: "imgs/products/sfhd.jpg",
    img2: "imgs/products/sfhd1.jpg",
    img3: "imgs/products/sfhd2.jpg",
    img4: "imgs/products/sfhd3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "WATCH, PLAY, CONNECT Samsung T5300 Full HD Flat Smart TV THAT BRINGS YOU ColorPur Color makes watching videos feel almost like you're there. It enables the TV to express a huge range of colors for optimal picture performance, and an immersive viewing experience. HD picture quality Enjoy your HD TV in the digital age we live in. Once you watch images on HDTV with vivid, vivid detail, you can be sure that you will never go back to standard definition devices or to analog TV. ",
  },
  {
    id: 12,
    name: "Samsung 43 Inch 4K UHD Smart",
    price: 7600,
    brand: "Samsung",
    series : "Mid Tier",
    img0: "imgs/products/1uhd.jpg",
    img1: "imgs/products/uhd.jpg",
    img2: "imgs/products/uhd1.jpg",
    img3: "imgs/products/uhd2.jpg",
    img4: "imgs/products/uhd3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "Brand: Samsung Model number: UA43AU7000UXEG Color: Black TV type: Smart TV Series: 7 Stand size: 841.7 x 192.5 mm Dimensions of TV with stand: 963.9 x 627.8 x 192.5 mm Dimensions of TV without stand: 963.9 x 558.9 x 59.6 mm Display Screen size: 43 inches Resolution: 3840 x 2160 pixels Color: PurColor Picture processor: Crystal processor 4K Picture quality Index: 2000 ",
  },
  {
    id: 13,
    name: "TORNADO 43 Inch Shield Smart",
    price: 7599,
    brand: "TORNADO",
    series : "Mid Tier",
    img0: "imgs/products/1tornado.jpg",
    img1: "imgs/products/tornado.jpg",
    img2: "imgs/products/tornado1.jpg",
    img3: "imgs/products/tornado2.jpg",
    img4: "imgs/products/tornado3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "TORNADO Shield Smart Anti-broken LED TV, Screen Size : 43 Inch, Resolution : 1920 x 1080, Aspect Ratio : 16:09,Contrast Ratio : 1:1200, Viewing Angle : 178°, Operating System : TORNADO Portal, With Built-In Receiver, Web Browser, Communication With YouTube, Shahid VIP, Watch It Application, Screen Mirroring, Connect With WiFi, USB Input : Video - Photos - Music, Rf In : 1, HDMI : 2,USB : 2, Video In : 1, Audio Output Power : 10 Watt x 2, Country Of Origin : Egypt, Warranty : 3 Years Full Free Warranty ",
  },
  {
    id: 14,
    name: "Premium 50 Inch 4K QLED",
    price: 6400,
    brand: "Premium",
    series : "Mid Tier",
    img0: "imgs/products/1qled.jpg",
    img1: "imgs/products/qled.jpg",
    img2: "imgs/products/qled1.jpg",
    img3: "imgs/products/qled2.jpg",
    img4: "imgs/products/qled3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "Unique and fashionable design. Lightweight. Made of high quality materials Exact size and fitting. Unique and fashionable design. ",
  },
  {
    id: 15,
    name: "Unionaire 32 inch HD LED",
    price: 2299,
    brand: "Unionaire",
    series : "Low Tier",
    img0: "imgs/products/1unionaire.jpg",
    img1: "imgs/products/unionaire.jpg",
    img2: "imgs/products/unionaire1.jpg",
    img3: "imgs/products/unionaire2.jpg",
    img4: "imgs/products/unionaire3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "Brand Unionaire Model number L32UT420 DisplayDisplay type HD LED Screen size 32 inches Resolution 1366 x 768 AudioSpeaker Sound output 2 x 10 W Connectivity2 HDMI ports 2 USB ports AccessoriesRemote control Yes ",
  },
  {
    id: 16,
    name: "LG 43 inches UHD 4K Smart",
    price: 7888,
    brand: "LG",
    series : "Mid Tier",
    img0: "imgs/products/1lg.jpg",
    img1: "imgs/products/lg.jpg",
    img2: "imgs/products/lg1.jpg",
    img3: "imgs/products/lg2.jpg",
    img4: "imgs/products/lg3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "FeaturesBrand LG Model 43UP7550PVG Type of processor A5 AI Processor 4K Number of sound channels 2 Design Cinema screen DisplayNano color Yes Nano accuracy Yes PlatformOperating system webOS Smart TV Number of CPUs Quad Video and picture qualityAI upscaling 4K Upscaling Image enhancing Yes AI brightness control Yes Filmmaker mode Yes Dynamic tone mapping HDR dynamic tone mapping HEVC 4K at 60P 10 bit VP9 Video decoder 4K at 60P 10 bit AV1 Video decoder 4K at 60P ",
  },
  {
    id: 17,
    name: "Samsung 65 Inche Neo QLED 8K Smart",
    price: 48000,
    brand: "Samsung",
    series : "High Tier",
    img0: "imgs/products/1smsng.jpg",
    img1: "imgs/products/smsng.jpg",
    img2: "imgs/products/smsng1.jpg",
    img3: "imgs/products/smsng2.jpg",
    img4: "imgs/products/smsng3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "SpecificationsBrand Samsung Model QA65QN800AUXEGDisplayScreen Size 65 Inches Resolution 7680 x 4320 Video Picture Engine Quantum Processor 8K HDR High Dynamic Range Quantum HDR 32x HDR 10 Yes Contrast Quantum Matrix Technology Pro Color Volume 100 Color Volume Viewing Angle Ultra Viewing Angle Contrast Enhancer Yes Auto Motion Plus Yes Film Mode Yes AudioDolby Digital Plus Yes Sound Output RMS 70W Speaker Type 422CH Bluetooth Audio Yes Smart ServicesSamsung SMART TV Works with Google Assistant ",
  },
  {
    id: 18,
    name: "ATA 32 Inch HD LED",
    price: 2150,
    brand: "ATA",
    series : "Low Tier",
    img0: "imgs/products/1ata.jpg",
    img1: "imgs/products/ata.jpg",
    img2: "imgs/products/ata1.jpg",
    img3: "imgs/products/ata2.jpg",
    img4: "imgs/products/ata3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "Brand : ATA Model Number : 32DN4 LE Size: 32 Inch Color : Black Resolution: 1366 x 768 (HD) USB : 2 HDMI : 2 VGA : 1 AV In Put : 1 AV Out Put : 1 Media Support All Extension ",
  },
  {
    id: 19,
    name: "Contex 40 inches FHD",
    price: 3299,
    brand: "Contex",
    series : "Low Tier",
    img0: "imgs/products/1contex.jpg",
    img1: "imgs/products/contex.jpg",
    img2: "imgs/products/contex1.jpg",
    img3: "imgs/products/contex2.jpg",
    img4: "imgs/products/contex3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "Harmonizes with your space and add sophisticated ambience Delivers superior picture quality with enhanced color purity Maintains accurate color, even from the sides, and allows everyone to enjoy the realistic picture Specifications Colour Name Black Model Name CON40N30NFA1A Model Number CON40N30NFA1A Number of HDMI Ports 2 Number of USB Ports 2 Screen Size 40 inch ",
  },
  {
    id: 20,
    name: "LG 43 Inch FHD LED",
    price: 6199,
    brand: "LG",
    series : "Mid Tier",
    img0: "imgs/products/1lgk.jpg",
    img1: "imgs/products/lgk.jpg",
    img2: "imgs/products/lgk1.jpg",
    img3: "imgs/products/lgk2.jpg",
    img4: "imgs/products/lgk3.jpg",
    category: "TVs",
    stars: 4,
    description:
      "Type LED TVs Diagonal: 43  Dimensions: 63 height 98 width Resolution: 1920x1080 HD format: FULL HD Screen format: 16: 9 Curved screen: no LED backlight type: DIRECT LED Active HDR Update frequency: 50 Hz Color Enhancement Technology: Dynamic Color Clarity Improvement Technology: True Motion Noise Reduction System: Yes IPS Display Total Output Power: 20 W Number of Speakers: 2 Sound System: 2.0 Sound Processing Technology: Virtual Surround Plus, Clear Voice Surround sound: yes Dolby Digital: Audio audio formats support Quad Core Processor ",
  },
  {
    id: 21,
    name: "Dell G15 15-5510 Gaming laptop ",
    price: 15740,
    brand: "Dell",
    series : "Mid Tier",
    img0: "imgs/products/1dellg.jpg",
    img1: "imgs/products/dellg.jpg",
    img2: "imgs/products/dellg1.jpg",
    img3: "imgs/products/dellg2.jpg",
    img4: "imgs/products/dellg3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Dell G15 15-5510 Gaming laptop - Intel Core i5-10500H 6Cores, 8GB RAM, 512GB SSD, Nvidia Geforce GTX1650 4GB GDDR6 Graphics, 15.6 FHD IPS 120Hz, Backlit Keyboard, UBUNTU - Shadow Grey ",
  },
  {
    id: 22,
    name: "Acer Predator Helios 300 Gaming Laptop",
    price: 29000,
    brand: "Acer",
    series : "High Tier",
    img0: "imgs/products/1acerp.jpg",
    img1: "imgs/products/acerp.jpg",
    img2: "imgs/products/acerp1.jpg",
    img3: "imgs/products/acerp2.jpg",
    img4: "imgs/products/acerp3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Acer gaming laptops deliver advanced performance for all gamers. The Predator lineup of gaming PCs and accessories are ideal for everyday gamers who need powerful products that can handle daily use and overclocking. The Acer Predator Helios 300 PH315-54 is powered up with the latest 11th Generation Intel Core i7 processor, giving you power, speed, and intelligent processing when you need it most. ",
  },
  {
    id: 23,
    name: "IdeaPad Gaming 3 Laptop",
    price: 15999,
    brand: "Leonovo",
    series : "Mid Tier",
    img0: "imgs/products/1ideapad.jpg",
    img1: "imgs/products/ideapad.jpg",
    img2: "imgs/products/ideapad1.jpg",
    img3: "imgs/products/ideapad2.jpg",
    img4: "imgs/products/ideapad3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Processor AMD Ryzen 5 5600H (6C / 12T, 3.3 / 4.2GHz, 3MB L2 / 16MB L3), Graphics NVIDIA GeForce GTX 1650 4GB GDDR6 Chipset AMD SoC Platform Memory 1x 8GB SO-DIMM DDR4-3200, Storage 512GB SSD M.2 2280 PCIe 3.0x4 N, VMe, Audio Chip High Definition (HD) Audio, Realtek ALC3287 codec Speakers Stereo speakers, 2W x2, Nahimic Audio Camera 720p with Camera Shutter Microphone 2x, Array Battery Integrated 45Wh, Power Adapter 135W Slim Tip (3-pin),",
  },
  {
    id: 24,
    name: "ASUS Vivobook X571LH-BQ007T Laptop",
    price: 23000,
    brand: "ASUS",
    series : "High Tier",
    img0: "imgs/products/1vivo.jpg",
    img1: "imgs/products/vivo.jpg",
    img2: "imgs/products/vivo1.jpg",
    img3: "imgs/products/vivo2.jpg",
    img4: "imgs/products/vivo3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Powered by up to the latest Intel Core i7 processor with 16GB RAM and NVIDIA GeForce GTX1650 Ti graphics, VivoBook 15 includes integrated Intel Wi-Fi 6 (802.11ax) that delivers superfast networking speeds for quick transfers of large files, responsive online gaming, and super-smooth video chats. ",
  },
  {
    id: 25,
    name: "HP 15-DY2095WM Laptop",
    price: 10999,
    brand: "HP",
    series : "Low Tier",
    img0: "imgs/products/1hpdy.jpg",
    img1: "imgs/products/hpdy.jpg",
    img2: "imgs/products/hpdy1.jpg",
    img3: "imgs/products/hpdy2.jpg",
    img4: "imgs/products/hpdy3.jpg",
    category: "laptops",
    stars: 4,
    description:
      " HP 15-DY2095WM Laptop - 11th Intel core i5-1135G7, 8GB RAM , 256GB SSD, Intel Iris Xe Graphics, 15.6 FHD (1920 x 1080) micro-edge anti-glare 250 nits, Windows 11 - Natural Silver ",
  },
  {
    id: 26,
    name: "ASUS TUF Gaming A15 Laptop",
    price: 22900,
    brand: "ASUS",
    series : "High Tier",
    img0: "imgs/products/1tuf.jpg",
    img1: "imgs/products/tuf.jpg",
    img2: "imgs/products/tuf1.jpg",
    img3: "imgs/products/tuf2.jpg",
    img4: "imgs/products/tuf3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Geared for serious gaming and real-world durability, the TUF Gaming A15 is a fully-loaded Windows 11 gaming laptop that can carry you to victory. Powered by the latest 4000 series AMD Ryzen 7 CPU and Nvidia GeForce RTX 3050 GPU, action-packed gameplay is fast, fluid, and fully saturates speedy IPS-level displays up to 144Hz. Even while boasting a smaller and more portable chassis than its predecessors, this gaming laptop also features a larger 90Wh battery for superior battery life. Efficient self-cleaning cooling combines with TUF's signature military-grade durability to make this battle-tested road warrior a reliable ally for gamers on the go. ",
  },
  {
    id: 27,
    name: "Dell G3 3500 Gaming Laptop",
    price: 16333,
    brand: "Dell",
    series : "Mid Tier",
    img0: "imgs/products/1dellgg.jpg",
    img1: "imgs/products/dellgg.jpg",
    img2: "imgs/products/dellgg1.jpg",
    img3: "imgs/products/dellgg2.jpg",
    img4: "imgs/products/dellgg3.jpg",
    category: "laptops",
    stars: 4,
    description:
      " Dell G3 Gaming Core i5 Good Quality with a high end Dell G5 15-5500 Gaming laptop - Intel Core i5-10300H, 8GB RAM , 1TB HDD + 256GB SSD, Nvidia Geforce GTX 1650 Ti 4GB GDDR6 Graphics, 15.6' FHD IPS 120Hz, Backlit Keyboard, Windows 10 - Black Easy to use Personal Computer type ",
  },
  {
    id: 28,
    name: "MSI GF65 Thin 9SD Gaming Laptop",
    price: 19000,
    brand: "MSI",
    series : "High Tier",
    img0: "imgs/products/1msi.jpg",
    img1: "imgs/products/msi.jpg",
    img2: "imgs/products/msi1.jpg",
    img3: "imgs/products/msi2.jpg",
    img4: "imgs/products/msi3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Brand: MSI Software Operating system: DOS Hard drive Hard Disk Capacity: 512GB Hard Disk Interface: SSD Memory RAM Memory capacity: 16GB Type: DDR4 Processor Processor: Intel Core i7-9750H Cache: 12 MB SmartCache Number of Cores: 6 Number of Threads: 12 Processor Base Frequency: 2.60 GHz Screen Display: 15.6 Inch FHD 1920x1080 Touchscreen: No",
  },
  {
    id: 29,
    name: "ASUS ROG Strix Scar 15",
    price: 64999,
    brand: "ASUS",
    series : "High Tier",
    img0: "imgs/products/1rog.jpg",
    img1: "imgs/products/rog.jpg",
    img2: "imgs/products/rog1.jpg",
    img3: "imgs/products/rog2.jpg",
    img4: "imgs/products/rog3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Compete at the highest level of Windows 11 gaming with the ROG Strix SCAR 15 gaming laptop. Take on any challenge with a powerful 12th Gen Intel Core i9-12900H CPU and GeForce RTX 3070 Ti GPU. ROG Intelligent Cooling lets the GPU crank all the way up to 150W of power and next gen DDR5 RAM and PCIe 4.0 SSD lets you spend less time waiting and more time playing or creating. Don’t worry about slow external transfer speeds or connecting to multiple displays with the Thunderbolt 4 port. With a competitive edge this sharp, you can dominate any arena.",
  },
  {
    id: 30,
    name: "Lenovo IdeaPad Gaming 3 15IHU6 Laptop",
    price: 15888,
    brand: "Lenovo",
    series : "Mid Tier",
    img0: "imgs/products/1lenovoi.jpg",
    img1: "imgs/products/lenovoi.jpg",
    img2: "imgs/products/lenovoi1.jpg",
    img3: "imgs/products/lenovoi2.jpg",
    img4: "imgs/products/lenovoi3.jpg",
    category: "laptops",
    stars: 4,
    description:
      "Lenovo IdeaPad Gaming 3 15IHU6 Laptop - 11th Intel Core i5-11300H, 8GB RAM, 256GB SSD, NVIDIA GeForce GTX 1650 4GB GDDR6 Graphics, 15.6 FHD (1920x1080) IPS 120Hz, Backlit Keyboard, Widnows 11 - Black ",
  },
  {
    id: 31,
    name: "G-SHOCK Men's Wrist Watch",
    price: 5181,
    brand: "Casio",
    series : "High Tier",
    img0: "imgs/products/1gshock.jpg",
    img1: "imgs/products/gshock.jpg",
    img2: "imgs/products/gshock1.jpg",
    img3: "imgs/products/gshock2.jpg",
    img4: "imgs/products/gshock3.jpg",
    category: "watches",
    stars: 4,
    description: "The Best for Casual wear",
  },
  {
    id: 32,
    name: "CASIO Men's Stainless Steel Analog",
    price: 764,
    brand: "CASIO",
    series : "Mid Tier",
    img0: "imgs/products/1canalog.jpg",
    img1: "imgs/products/canalog.jpg",
    img2: "imgs/products/canalog1.jpg",
    img3: "imgs/products/canalog2.jpg",
    img4: "imgs/products/canalog3.jpg",
    category: "watches",
    stars: 4,
    description:
      "Casio aims to provide the important things you keep close in life. Continuing to create the things to that are most important to users.",
  },
  {
    id: 33,
    name: "HUGO BOSS Men's Leather Analog",
    price: 2801,
    brand: "XiaHUGO BOSSomi",
    series : "High Tier",
    img0: "imgs/products/1hugo.jpg",
    img1: "imgs/products/hugo.jpg",
    img2: "imgs/products/hugo1.jpg",
    img3: "imgs/products/hugo2.jpg",
    img4: "imgs/products/hugo3.jpg",
    category: "watches",
    stars: 4,
    description:
      "Hugo boss ag, often styled as boss, is a german luxury fashion house headquartered in metzingen, baden-württemberg.",
  },
  {
    id: 34,
    name: "HUAWEI WATCH GT 3",
    price: 5885,
    brand: "HUAWEI",
    series : "High Tier",
    img0: "imgs/products/1hgt.jpg",
    img1: "imgs/products/hgt.jpg",
    img2: "imgs/products/hgt1.jpg",
    img3: "imgs/products/hgt2.jpg",
    img4: "imgs/products/hgt3.jpg",
    category: "watches",
    stars: 4,
    description:
      "Smart Watch,Jupiter-B19V,Stainless Steel Case,Open Market,Smart Watch, Internal Lithium Ion Battery*1/Without Charger",
  },
  {
    id: 35,
    name: "CASIO Boys' Water Resistant",
    price: 590,
    brand: "CASIO",
    series : "Mid Tier",
    img0: "imgs/products/1water.jpg",
    img1: "imgs/products/water.jpg",
    img2: "imgs/products/water1.jpg",
    img3: "imgs/products/water2.jpg",
    img4: "imgs/products/water3.jpg",
    category: "watches",
    stars: 4,
    description:
      "Casio aims to provide the important things you keep close in life. Continuing to create the things that are most important to users.",
  },
  {
    id: 36,
    name: "Xiaomi Mi Watch Black",
    price: 2399,
    brand: "Xiaomi",
    series : "High Tier",
    img0: "imgs/products/1mi.jpg",
    img1: "imgs/products/mi.jpg",
    img2: "imgs/products/mi1.jpg",
    img3: "imgs/products/mi2.jpg",
    img4: "imgs/products/mi3.jpg",
    category: "watches",
    stars: 4,
    description:
      "AMOLED HD 1.39” large display, Corning Gorilla Glass 3, 16 days of long battery life with one charge on normal use",
  },
  {
    id: 37,
    name: "LACOSTE Men's Metal Analog",
    price: 2632,
    brand: "LACOSTE",
    series : "Mid Tier",
    img0: "imgs/products/1laco.jpg",
    img1: "imgs/products/laco.jpg",
    img2: "imgs/products/laco1.jpg",
    img3: "imgs/products/laco2.jpg",
    img4: "imgs/products/laco3.jpg",
    category: "watches",
    stars: 4,
    description: "Elegant analog metal for classy dates",
  },
  {
    id: 38,
    name: "Men's Leather Chronograph",
    price: 1966,
    brand: "Caiso",
    series : "Mid Tier",
    img0: "imgs/products/1chrono.jpg",
    img1: "imgs/products/chrono.jpg",
    img2: "imgs/products/chrono1.jpg",
    img3: "imgs/products/chrono2.jpg",
    img4: "imgs/products/chrono3.jpg",
    category: "watches",
    stars: 4,
    description:
      "Crafted with premium quality band material to prevent sweat and skin irritations Intricately decked that assures for wear-resistance",
  },
  {
    id: 39,
    name: "Amazfit GTS 2 Smartwatch",
    price: 3299,
    brand: "Amazfit",
    series : "High Tier",
    img0: "imgs/products/1Amazfit.jpg",
    img1: "imgs/products/Amazfit.jpg",
    img2: "imgs/products/Amazfit1.jpg",
    img3: "imgs/products/Amazfit2.jpg",
    img4: "imgs/products/Amazfit3.jpg",
    category: "watches",
    stars: 4,
    description:
      "The watch also incorporates diamond-like carbon (oDLC) coating to provide a more scratch-resistant and wear-resistant screen that greatly enhances the glass quality and lifetime",
  },
  {
    id: 40,
    name: "DANIEL WELLINGTON Men's Classic",
    price: 410,
    brand: "DANIEL WELLINGTON",
    series : "Low Tier",
    img0: "imgs/products/1daniel.jpg",
    img1: "imgs/products/daniel.jpg",
    img2: "imgs/products/daniel1.jpg",
    img3: "imgs/products/daniel2.jpg",
    img4: "imgs/products/daniel3.jpg",
    category: "watches",
    stars: 4,
    description:
      "Perfectly designed with high precision Lightweight, durable and comfortable to wear",
  },
];

// set items in local storage
localStorage.setItem("products", JSON.stringify(productsList));
